### ISSUE TITLE
Release binary dcm2niix does not pass batch.sh

### ISSUE THREAD

**Issue by cfhammill** [neurolabusc/dcm_qa_ct#1]
I'm working on a PR to dcm2niix to fix a floating point issue with the gantry tilt calculation (discussed https://github.com/rordenlab/dcm2niix/issues/782#issuecomment-1944514059). I was going to attempt to add a synthetic example that shows the issue to this repo, but in testing the current release version I discovered that the release version does not pass the existing checks.

I tested as follows:

```
git clone https://github.com/neurolabusc/dcm_qa_ct
cd dcm_qa_ct
curl -L -O https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20230411/dcm2niix_lnx.zip
unzip dcm2niix_lnx.zip
## note examnam is a typo in ./batch.sh, should be exenam
examnam=./dcm2niix ./batch.sh
```

I get some regular looking output (I can add if useful), followed by

```
diff -x ''\''.*'\''' -br -I ConversionSoftwareVersion /mnt/data/home/HammillC/documents/dcm_qa_ct/Ref/_2.json /mnt/data/home/HammillC/documents/dcm_qa_ct/Out/_2.json
2a3
>       "ImagingFrequency": 0,
Binary files /mnt/data/home/HammillC/documents/dcm_qa_ct/Ref/_2.nii and /mnt/data/home/HammillC/documents/dcm_qa_ct/Out/_2.nii differ
```

For all files, `"ImagingFrequency": 0` is missing from the reference. And for two files the image binaries differ. At first I thought the binary diff was just too sensitive, but it looks like the header does actually differ.

```python
import nibabel
im1 = nibabel.Nifti1Image.from_filename("/mnt/data/home/HammillC/documents/dcm_qa_ct/Ref/1F_STEREOTAXIS_Head_201.nii")
im2 = nibabel.Nifti1Image.from_filename("/mnt/data/home/HammillC/documents/dcm_qa_ct/Out/1F_STEREOTAXIS_Head_201.nii")

for tag in ["srow_x", "srow_y", "srow_z"]: print(im1.header[tag])
```

```
[ -0.48242188   0.           0.         123.5       ]
[ 0.0000000e+00  5.0871015e-01  2.3841858e-07 -2.1813747e+02]
[0.0000000e+00 1.5307471e-01 2.2482941e+00 6.6412402e+02]
```

```python
for tag in ["srow_x", "srow_y", "srow_z"]: print(im2.header[tag])
```

```
[ -0.48242188   0.          -0.         123.5       ]
[  -0.            0.45749205    0.         -218.13747   ]
[0.0000000e+00 1.5307471e-01 2.3708091e+00 6.6412402e+02]
```

difference clearly visible in row 2, column 2, 0.508 v.s. 0.457.

The voxel data is the same though,

```python
import numpy as np

np.abs(im1.get_fdata() - im2.get_fdata()).max()
> 0.0
```

**Comment by neurolabusc** [comment]
Perhaps you can make a PR with suggested tests and I can run a CT validation. Obviously, ImagingFrequency is specific to MR, and not present in CT. I suspect that [the code](https://github.com/rordenlab/dcm2niix/blob/fe2f26005109f396a4f828aa438241f73fc25fe8/console/nii_dicom_batch.cpp#L1223):
```
fprintf(fp, "\t\"ImagingFrequency\": %.10g,\n", d.imagingFrequency);
```
will exclude zeros if modified to read:
```
json_Float(fp, "\t\"ImagingFrequency\": %.10,\n", d.imagingFrequency);
```
The change in the s-form will need careful evaluation, as that looks like the shear component.

**Comment by neurolabusc** [comment]
@cfhammill please make sure that your modifications and PR are done on the development branch. The master branch always points to the current stable release, and the development branch is the upcoming stable release.

**Comment by neurolabusc** [comment]
Resolved with latest commit
